### ISSUE TITLE
How do we manage to bundle the documentation of all plugins into a Biogems website?

### ISSUE THREAD

**Issue by greenify** [bionode/bionode#10]
Following Max's advice I thought I just create issue for every open questions,  so that is is easier to track things.

Bruno: I'm a fan of having literate code and using docco. I think it's a good practice to write the comments as docs when you're writing the code, and that way you don't have to figure out where the documentation is.
However, this isn't of course an alternative to a global API doc. As I mentioned, some projects do global APIs manually, like underscore, express, nodejs and socket.io. However, something automatic would be better. I'm currently exploring doxx as it seems to be able to generate a single doc for multiple modules. If doxx can solve most of the problem, we can then tweak it to generate an output with some of Biogems features.

**Comment by bmpvieira** [comment]
Sounds good, displaying the README.md in the registry is what [NPM is also doing](https://www.npmjs.com/package/bionode) and seems to be the simplest solution. As for combining all the docs into a global API, I'm just concatenating the [docco html](http://rawgit.com/bionode/bionode-ncbi/master/docs/bionode-ncbi.html) (with some tweaks) for [doc.bionode.io](http://doc.bionode.io), but this could be improved.
I'm closing this as the documentation in the [BioJS registry](http://biojs.io) issue seems solved. As for global documentation, we can continue at bionode/bionode#27
