### ISSUE TITLE
How do you define a bio-core?

### ISSUE THREAD

**Issue by greenify** [bionode/bionode#11]
Seb: Why do you have the sequence class as core?
Seb: Something that I am imagining that should go inside this core could be a  "GenericParser" which all parsers can inherit. After all they receive text and output an object. On the other side that might change too: arrays of binary data could be needed or with the upcoming ES6 Harmony browsers might finally support more structures.

Bruno: I think bio core should have helpers or util functions that are reused by most of the other bio modules.
The Sequence methods fit that description, although the reason why I have them in core is more historical than anything else. The first bionode module started as a way to provide those functions client side to the Afra project, while also being available for server side usage.
They should probably be moved to a specific bionode-sequence module, but then the bionode module would be empty since I don't have helper functions for now. In that case, the bionode module could become instead of the "core" module the "meta" module that links the other modules together in some kind of framework.

**Comment by bmpvieira** [comment]
I think we should let models/schemas evolve naturally and only worry about that when it becomes a real issue for collaboration/integration among modules. Right now, this hasn't been a problem for `bionode`, and [`biojs-model`](https://github.com/biojs/biojs-model) also seems still empty. I agree that standards are good, but I'm always afraid we might [overthink this](https://xkcd.com/927/) and end up with something like [Chado](http://gmod.org/wiki/Chado_Tables). The real standard we should worry about are JSON and [Protobuf](https://developers.google.com/protocol-buffers/). Object's schemas are easy to transform in a JavaScript pipeline. Also, Bionode tries to be more [functional than object oriented](http://timruffles.github.io/you-probably-dont-want-an-object), which kind of solves the issue.
