### ISSUE TITLE
curl not installed by default on debian machines

### ISSUE THREAD

**Issue by fourpartswater** [bionode/bionode#18]
Hi... curl isn't installed by default on debian jessie (and possibly others) 
wget is installed where curl isn't so maybe you could fall back to that?

**Comment by c089** [comment]
Thanks for raising this issue. I beleive the best way to solve this issue be to use a javascript http client to handle downloads instead of relying on more CLI tools.

Cuplprit is the [bionode-sra Makefile](https://github.com/bionode/bionode-sra/blob/master/sra/Makefile).

**Comment by bmpvieira** [comment]
Moving discussion to #29
