### ISSUE TITLE
curses.h missing on debian jessie

### ISSUE THREAD

**Issue by fourpartswater** [bionode/bionode#19]
Compilation of something was failing due to no curses.h from libncurses5-dev on debian jessie

**Comment by wookoouk** [comment]
Have you tried:
sudo apt-get install libncurses5-dev
or if that fails
sudo apt-get install ncurses-devel ncurses

**Comment by bmpvieira** [comment]
This is related to bionode/bionode#29, we need to solved that.
Feel free to continue the discussion there.
