### ISSUE TITLE
module links in readme are 404

### ISSUE THREAD

**Issue by acthp** [bionode/bionode#30]
e.g.

https://github.com/bionode/bionode-vcf

**Comment by iliocatallo** [comment]
What is the correct link to the bionode-vcf project?

**Comment by bmpvieira** [comment]
Hey, the status of some modules is "request" which mean the community has requested those modules but they're not available yet. Sorry if this is confusing, we should improve the readme.
However, regarding vcf, there is a work-in-progress module currently at https://github.com/shyamrallapalli/bionode-vcf

**Comment by bmpvieira** [comment]
The [old module list table](https://github.com/bionode/bionode/blob/3db22531ed976b27576cda15a42638d8779ea58d/README.md) got removed in d7512ccef1da98e02e52e5c6156625e5a73cb450 in favour of [https://github.com/search?q=org:bionode+topic:tool](https://github.com/search?q=org:bionode+topic:tool).
