### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by bmpvieira** [bionode/bionode#38]
We already have a [CODE_OF_CONDUCT.md](https://github.com/bionode/bionode/blob/master/CODE_OF_CONDUCT.md) file in the main repository, but it should be included with every module/tool. That can be done by just copying this file or in a more technical way by doing ```npm install -g covgen``` and then for each repo folder ```covgen mail@bionode.io```.

We should also [PR the contributor-covenant website](http://contributor-covenant.org/#who) to be added to their list.

WIP:
- [x] [bionode](https://github.com/bionode/bionode)
- [x] [bionode-ncbi](https://github.com/bionode/bionode-ncbi)
- [x] [bionode-watermill](https://github.com/bionode/bionode-watermill)
- [x] [bionode-fastq](https://github.com/bionode/bionode-fastq)
- [x] [bionode-fasta](https://github.com/bionode/bionode-fasta)
- [x] [fasta-parser](https://github.com/bionode/fasta-parser)
- [x] [bionode-vcf](https://github.com/bionode/bionode-vcf)
- [x] [bionode-gff](https://github.com/bionode/bionode-gff)
- [x] [bionode-obo](https://github.com/bionode/bionode-obo)
- [x] [bionode-sra](https://github.com/bionode/bionode-sra)
- [x] [bionode-sam](https://github.com/bionode/bionode-sam)
- [x] [bionode-bwa](https://github.com/bionode/bionode-bwa)
- [x] [bionode-bbi](https://github.com/bionode/bionode-bbi)
- [x] [bionode-blast](https://github.com/bionode/bionode-blast)
- [x] [bionode-go](https://github.com/bionode/bionode-go)
- [x] [bionode-quickgo](https://github.com/bionode/bionode-quickgo)
- [x] [bionode-scripts](https://github.com/bionode/bionode-scripts)
- [x] [bionode-seq](https://github.com/bionode/bionode-seq)
- [x] [bionode-sge](https://github.com/bionode/bionode-sge)
- [x] [bionode-template](https://github.com/bionode/bionode-template)
- [x] [biohacker](https://github.com/bionode/biohacker)
- [x] [try-bionode](https://github.com/bionode/try-bionode)
- [x] [get-bionode](https://github.com/bionode/get-bionode)
- [x] [docker-browser-server](https://github.com/bionode/docker-browser-server)
- [x] [bionode-examples](https://github.com/bionode/bionode-examples)
- [x] [bionode.github.io](https://github.com/bionode/bionode.github.io)
- [x] [doc.bionode.io](https://github.com/bionode/doc.bionode.io)
- [x] [github-project-public](https://github.com/bionode/github-project-public)
- [x] [studyGroup](https://github.com/bionode/studyGroup)
- [x] [gsoc16](https://github.com/bionode/gsoc16)
- [x] [GSoC17](https://github.com/bionode/GSoC17)
- [x] [bionode-flow](https://github.com/bionode/bionode-flow)
- [x] [bionode-example-dat-gasket](https://github.com/bionode/bionode-example-dat-gasket)

**Comment by Rudani** [comment]
WIP:
- [x] [bionode](https://github.com/bionode/bionode)
- [ ] [bionode-ncbi](https://github.com/bionode/bionode-ncbi)
- [ ] [bionode-watermill](https://github.com/bionode/bionode-watermill)
- [ ] [bionode-fastq](https://github.com/bionode/bionode-fastq)
- [ ] [bionode-fasta](https://github.com/bionode/bionode-fasta)
- [x] [fasta-parser](https://github.com/bionode/fasta-parser)
- [ ] [bionode-vcf](https://github.com/bionode/bionode-vcf)
- [ ] [bionode-gff](https://github.com/bionode/bionode-gff)
- [ ] [bionode-obo](https://github.com/bionode/bionode-obo)
- [ ] [bionode-sra](https://github.com/bionode/bionode-sra)
- [ ] [bionode-sam](https://github.com/bionode/bionode-sam)
- [ ] [bionode-bwa](https://github.com/bionode/bionode-bwa)
- [ ] [bionode-bbi](https://github.com/bionode/bionode-bbi)
- [ ] [bionode-blast](https://github.com/bionode/bionode-blast)
- [ ] [bionode-go](https://github.com/bionode/bionode-go)
- [ ] [bionode-quickgo](https://github.com/bionode/bionode-quickgo)
- [ ] [bionode-scripts](https://github.com/bionode/bionode-scripts)
- [ ] [bionode-seq](https://github.com/bionode/bionode-seq)
- [ ] [bionode-sge](https://github.com/bionode/bionode-sge)
- [ ] [bionode-template](https://github.com/bionode/bionode-template)
- [ ] [biohacker](https://github.com/bionode/biohacker)
- [ ] [try-bionode](https://github.com/bionode/try-bionode)
- [ ] [get-bionode](https://github.com/bionode/get-bionode)
- [ ] [docker-browser-server](https://github.com/bionode/docker-browser-server)
- [ ] [bionode-examples](https://github.com/bionode/bionode-examples)
- [ ] [bionode.github.io](https://github.com/bionode/bionode.github.io)
- [ ] [github-project-public](https://github.com/bionode/github-project-public)
- [ ] [studyGroup](https://github.com/bionode/studyGroup)
- [ ] [gsoc16](https://github.com/bionode/gsoc16)
- [ ] [bionode-flow](https://github.com/bionode/bionode-flow)
- [ ] [bionode-example-dat-gasket](https://github.com/bionode/bionode-example-dat-gasket)

**Comment by ayangromano** [comment]
Hello! I'd be happy to assist with this! 👍

**Comment by bmpvieira** [comment]
Thanks @ayangromano! Please go forward with this and open pull requests. Check the [contributing guidelines](https://github.com/bionode/bionode/blob/master/CONTRIBUTING.md). You can also come chat with us at http://gitter.im/bionode/bionode

**Comment by bmpvieira** [comment]
Thank you @ayangromano for all this! I also did a PR to add Bionode to the list of adopters. 
https://github.com/ContributorCovenant/contributor_covenant/pull/409
